# This is a basic workflow to help you get started with Actions

name: Deployment to Cloudhub on push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

env:
  applicationName: 'apiforce-cicd-demo-v1-dev'
  anypointUsername: apiforce
  anypointPassword: 3tjnJ#neQibH!B
  businessgroup: mboss
  artifactName: 'apiforce-cicd-demo-v1-dev'
  anypointEnvironment: 'DEV'
  propertiesEnvironment: 'dev'
  workerType: MICRO
  noOfWorkers: 1
  region: us-east-1
  vaultKey: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository branch
        uses: actions/checkout@v2
      
      - name: Check if something is cached
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-mvn-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-mvn-
            
      - name: Inject variables to pom
        uses: rlespinasse/github-slug-action@v3.x
 
      - name: Setup up JDK 1.8
        uses: actions/setup-java@v1
        with: 
          java-version: 1.8
 
      - name: Print Settings
        run: mvn help:effective-settings
 
      - name: Build Mule app with Maven
        run:
          mvn -B package --file pom.xml -DskipTests
 
      - name: Upload artifact to Git-Actions artifactory
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.artifactName}}
          path: ${{ github.workspace }}/target/*mule-application*.jar
          
  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:

      - name: Checkout Repository Branch
        uses: actions/checkout@v2

      - name: Check if something is cached    
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download artifact from artifactory
        uses: actions/download-artifact@v2
        with:
          name: ${{env.artifactName}}

      - name: Deploy to Cloudhub
        run: |
          artifactName=$(ls *.jar | head -1)
          mvn deploy -DmuleDeploy -e \
            -DanypointEnvironment=${{env.anypointEnvironment}} \
            -DpropertiesEnvironment=${{env.propertiesEnvironment}} \
            -DanypointUsername=${{ env.anypointUsername }} \
            -DanypointPassword=${{ env.anypointPassword }} \
            -Dbusinessgroup=${{ env.businessgroup }} \
            -DvaultKey=${{env.vaultKey}} \
            -Dregion=${{env.region}} \
            -DnoOfWorkers=${{env.noOfWorkers}} \
            -DworkerType=${{env.workerType}} \
            -DskipTests
